config/routes.rb
CodeChallenge::Application.routes.draw do
  get "admin_section/edit"

  get "admin_section/new"

  get "admin_section/show"

  post "admin_section/create"

  get "admin_section/destroy"

  get "admin_section/browse"

  post "admin_section/update"

  devise_for :admins

  devise_for :users

  get "problem/browse"

  get "problem/show"

  post "problem/answer"

  get "problem/result"

   root :to => 'problem#browse'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  attr_accessible :question, :title
end

app/models/solved.rb
class Solved < ActiveRecord::Base
  attr_accessible :problem_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin_section_controller.rb
class AdminSectionController < ApplicationController
  before_filter :authenticate_admin!

  def browse
    @problems = Problem.all
  end

  def new
  end

  def create
  	@problem = Problem.new
  	@problem.title = params[:title]
  	@problem.question = params[:question]
  	@problem.save
    file2 = File.new('input'+@problem.id.to_s,'w')
    file2.write(params[:testing_input])
    file2.close
    file2 = File.new('output'+@problem.id.to_s,'w')
    file2.write(params[:testing_output])
    file2.close
  	redirect_to admin_section_browse_path
  end

  def edit
  end

  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy
    redirect_to admin_section_browse_path
    `rm input#{params[:id]} output#{params[:id]}`
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/problem_controller.rb
class ProblemController < ApplicationController
  before_filter :authenticate_user!

  def browse
  	@problems = Problem.all
    if Solved.find_by_user_id(current_user.id)
      @solved_problems = Solved.where(user_id = current_user.id)
    else
      @solved_problems = []
    end
  end

  def show
  	@problem = Problem.find_by_id(params[:id])
  end

  def answer
  	file = params[:upload].tempfile
    extension = File.extname(params[:upload].original_filename)
    @id = params[:id]
  	@content = File.read(file)
    filename = current_user.username+extension
  	file2 = File.new(filename,'w')
  	file2.write(@content)
  	file2.close
  	if extension == ".c"
      `gcc #{filename}`
      @output = `./a.out < 'input'#{@id}`
    elsif extension == ".cpp"
      `g++ #{filename}`
       @output = `./a.out < 'input'#{@id}`
    elsif extension == ".py"
      @output = `python #{filename} < 'input'#{@id}`.chop
    elsif extension == ".rb"
      @output = `ruby #{filename} < 'input'#{@id}`.chop                                              
    end
  	if @output == File.read('output' + @id)
  		@result = 'Success'
      if !Solved.find_by_user_id_and_problem_id(current_user.id, params[:id])
        @solved = Solved.new
        @solved.problem_id = params[:id]
        @solved.user_id = current_user.id
        @solved.save
      end
  	else
  		@result = "Failure"
  	end
    `rm a.out`
    `rm #{filename}`
  end

  def result
  end
end

app/helpers/admin_section_helper.rb
module AdminSectionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/views/admin_section/browse.html.erb
<%= stylesheet_link_tag 'foundation' %>
<div class= "top-bar-section">
	<div class = "top-bar">
		<ul class = "left">
			<li class = "divider"></li>
			<li class = "active"><%= link_to "CODE CHALLENGE", admin_section_browse_path %></li>
			<li class = "active"><%= link_to "Browse", admin_section_browse_path %></li>
			<li class = "active"><%= link_to "Add Problem", admin_section_new_path %></li>
		</ul>
		<ul class = "right">
			<li class = "divider"></li>
			<li class = "active"><%= link_to current_admin.username, admin_section_browse_path %></li>
			<li class = "active"><%= link_to "Log Out", destroy_admin_session_path, :method => "delete" %></li>
		</ul>
	</div>
</div>

<% @problems.each do |problem| %>
<div class = "row" >
	<div class = "large-10 columns panel" >
		<%= problem.title %>
	</div>
	<div class = "large-2 columns panel" > 
		<%= link_to "Delete", admin_section_destroy_path(:id => problem.id) %>
	</div>
</div>
<% end %>

app/views/admin_section/destroy.html.erb
<h1>AdminSection#destroy</h1>
<p>Find me in app/views/admin_section/destroy.html.erb</p>

app/views/admin_section/edit.html.erb
<%= form_for @problem do |problem| %>
	<p>
		<%= problem.label :title %><br>
		<%= problem.text_field :title %>
	</p>
	<p>
		<%= problem.label :question %><br>
		<%= problem.text_area :question %>
	</p>
	<p>
		<%= label_tag(:testing_input, "Testing Input") %><br>
		<%= text_area_tag(:testing_input) %>
	</p>
	<p>
		<%= label_tag(:testing_output, "Testing Output") %><br>
		<%= text_area_tag(:testing_output) %>
	</p>
	<p>
		<%= submit_tag("Add Problem") %>
	</p>
<% end %>

app/views/admin_section/new.html.erb
<%= stylesheet_link_tag 'foundation' %>
<div class= "top-bar-section">
	<div class = "top-bar">
		<ul class = "left">
			<li class = "divider"></li>
			<li class = "active"><%= link_to "CODE CHALLENGE", admin_section_browse_path %></li>
			<li class = "active"><%= link_to "Browse", admin_section_browse_path %></li>
			<li class = "active"><%= link_to "Add Problem", admin_section_new_path %></li>
		</ul>
		<ul class = "right">
			<li class = "divider"></li>
			<li class = "active"><%= link_to current_admin.username, admin_section_browse_path %></li>
			<li class = "active"><%= link_to "Log Out", destroy_admin_session_path, :method => "delete" %></li>
		</ul>
	</div>
</div>


<%= form_tag( :controller => "admin_section", :action => "create" ) do %>
	<div class = "row">
		<p>
			<h4><%= label_tag(:title, "Title") %><h4>
			<%= text_field_tag(:title) %>
		</p>
		<p>
			<%= label_tag(:question, "Question") %>
			<%= text_area_tag(:question) %>
		</p>
		<p>
			<%= label_tag(:testing_input, "Testing Input") %>
			<%= text_area_tag(:testing_input) %>
		</p>
		<p>
			<%= label_tag(:testing_output, "Testing Output") %>
			<%= text_area_tag(:testing_output) %>
		</p>
		<p>
			<%= button_tag("Add Problem") %>
		</p>
	</div>
<% end %>

app/views/admin_section/show.html.erb
<h1>AdminSection#show</h1>
<p>Find me in app/views/admin_section/show.html.erb</p>

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeChallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/problem/answer.html.erb
<%= stylesheet_link_tag    "foundation" %>
<div class= "top-bar-section">
	<div class = "top-bar">
		<ul class = "left">
			<li class = "divider"></li>
			<li class = "active"><%= link_to "CODE CHALLENGE", problem_browse_path %></li>
			<li class = "active"><%= link_to "Browse", problem_browse_path %></li>
		</ul>
		<ul class = "right">
			<li class = "divider"></li>
			<li class = "active"><%= link_to current_user.username, problem_browse_path %></li>
			<li class = "active"><%= link_to "Log Out", destroy_user_session_path, :method => "delete" %></li>
		</ul>
	</div>
</div>
<% if @result == "Success" %>
	<p class = "callout panel">Congrats.You got the correct answer.Proceed to the next question</p>
<% end %>

app/views/problem/browse.html.erb
<%= stylesheet_link_tag    "foundation" %>
<% i = 1 %>

<div class= "top-bar-section">
	<div class = "top-bar">
		<ul class = "left">
			<li class = "divider"></li>
			<li class = "active"><%= link_to "CODE CHALLENGE", problem_browse_path %></li>
			<li class = "active"><%= link_to "Browse", problem_browse_path %></li>
		</ul>
		<ul class = "right">
			<li class = "divider"></li>
			<li class = "active"><%= link_to current_user.username, problem_browse_path %></li>
			<li class = "active"><%= link_to "Log Out", destroy_user_session_path, :method => "delete" %></li>
		</ul>
	</div>
</div>

<div class = 'row'>
	<% @problems.each do |problem| %>
		<div class = 'large-1 columns panel'>
			#<%= i %>
		</div>
		<div class = 'large-5 columns panel'>	
			<%= problem.title %>
		</div>
		<div class = 'large-3 columns panel' >
			<%= link_to "Go to Question", problem_show_path(:id => problem.id) %>
		</div>
		<% @check_solved = "Not Solved" %>
		<% if @solved_problems != nil %>
			<% @solved_problems.each do |s| %>
				<% if s.problem_id == problem.id %>
					<% @check_solved = "Solved" %>
				<% end %>
			<% end %>
		<% end %>
		<div class = 'large-3 columns panel'>
			<%= @check_solved %><br>
		</div>
		<% i = i + 1 %>
	<% end %><br>
</div>

app/views/problem/show.html.erb
<%= stylesheet_link_tag    "foundation" %>
<div class= "top-bar-section">
	<div class = "top-bar">
		<ul class = "left">
			<li class = "divider"></li>
			<li class = "active"><%= link_to "CODE CHALLENGE", problem_browse_path %></li>
			<li class = "active"><%= link_to "Browse", problem_browse_path %></li>
		</ul>
		<ul class = "right">
			<li class = "divider"></li>
			<li class = "active"><%= link_to current_user.username, problem_browse_path %></li>
			<li class = "active"><%= link_to "Log Out", destroy_user_session_path, :method => "delete" %></li>
		</ul>
	</div>
</div>
<div class = "row">
	<div class = "large-8 large-centered columns">
		<div class = "callout panel"><%= @problem.title %></div>
		<div class = "panel"><%= @problem.question %></div>
		<%= form_tag({:action => :answer, :id => @problem.id }, :multipart => true) do %>
			<%= file_field_tag 'upload' %>
			<%= button_tag 'Upload' %>
		<% end %>
	</div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>